import {test,expect} from './browser-fixtures';
for(const [width,height] of [[568,320],[844,390]])test(`开桌摘要与实际配置一致并复用 ${width}`,async({page})=>{
 await page.setViewportSize({width,height});
 const sent:any[]=[];
 await page.routeWebSocket('**/ws',ws=>{const server=ws.connectToServer();ws.onMessage(raw=>{const m=JSON.parse(String(raw));if(m.type==='createTables')sent.push(m);server.send(raw);});});
 await page.goto('/');
 await page.getByRole('navigation',{name:'主导航'}).getByRole('button',{name:'约局',exact:true}).click();
 await page.getByRole('button',{name:'开桌设置',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'开桌设置',exact:true});
 await dialog.getByLabel('玩法名称',{exact:true}).fill('配置回归');
 await dialog.getByRole('switch',{name:'四连风',exact:true}).click();
 await dialog.getByRole('switch',{name:'接庄比',exact:true}).click();
 await dialog.getByLabel('超时倒计时秒数',{exact:true}).fill('45');
 await expect(dialog).toContainText('再开始 45 秒超时倒计时');
 await expect(dialog).toContainText('四连风已关闭');
 await dialog.getByRole('button',{name:'下一步',exact:true}).click();
 await dialog.getByRole('button',{name:'下一步',exact:true}).click();
 await expect(dialog.locator('.setup-review')).toContainText('接庄比：关闭');
 await expect(dialog.locator('.setup-review')).toContainText('四连风：关闭');
 await expect(dialog.locator('.setup-review')).toContainText('超时倒计时 45 秒');
 await expect(dialog.locator('.setup-review')).toContainText('桌外累计');
 await dialog.getByRole('button',{name:'创建 1 桌',exact:true}).click();
 await expect(dialog).toHaveCount(0);
 await expect.poll(()=>page.evaluate(async()=>{const {client}=await import('/src/game-client.ts' as string);const table=client.state.tables.find((t:any)=>t.name==='配置回归'&&t.managed);return table?{fourWinds:table.rules.fourWinds,successorDouble:table.rules.successorDouble,overtime:table.settings.overtimeSeconds}:null;})).toEqual({fourWinds:false,successorDouble:false,overtime:45});
 expect(sent).toHaveLength(1);expect(sent[0].rules).toMatchObject({fourWinds:false,successorDouble:false});expect(sent[0].settings.overtimeSeconds).toBe(45);
 await page.getByRole('button',{name:'开桌设置',exact:true}).click();
 await expect(dialog).toContainText('已沿用上次开桌配置');
 await expect(dialog.getByRole('switch',{name:'四连风',exact:true})).toHaveAttribute('aria-checked','false');
 await expect(dialog.getByLabel('超时倒计时秒数',{exact:true})).toHaveValue('45');
});
