import sharp from 'sharp';
import {readFile,writeFile,mkdir,copyFile,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
const app=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const input=resolve(process.argv[2]);
const resources=resolve(app,'cocos-table/assets/resources');
await mkdir(resolve(resources,'tiles'),{recursive:true});
const poses=JSON.parse(await readFile(resolve(input,'poses.json'),'utf8'));
const catalog=process.argv.includes('--merge')?JSON.parse(await readFile(resolve(resources,'tile-atlas.json'),'utf8')):{};
for(const [name,pose]of Object.entries(poses)){
 if(/-(near|far)$/.test(name)||/^top-(left|right)$/.test(name)){await rm(resolve(resources,'tiles',name+'.png'),{force:true});await rm(resolve(resources,'tiles',name+'.png.meta'),{force:true});continue;}
 const source=resolve(input,pose.file),frames=[],cells=[];
 let left=pose.cell,top=pose.cell,right=0,bottom=0;
 for(let k=0;k<pose.kinds;k++){
  const raw=await sharp(source).extract({left:k%pose.columns*pose.cell,top:Math.floor(k/pose.columns)*pose.cell,width:pose.cell,height:pose.cell}).ensureAlpha().raw().toBuffer({resolveWithObject:true});
  cells.push(raw.data);
  for(let y=0;y<pose.cell;y++)for(let x=0;x<pose.cell;x++)if(raw.data[(y*pose.cell+x)*4+3]>8){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}
 }
 // Every face in one camera pose uses the same crop and anchor. Individual
 // alpha bounds otherwise make different glyphs subtly resize the tile body.
 const rect=pose.crop||{left,top,width:right-left+1,height:bottom-top+1};
 for(const data of cells){
  const image=await sharp(data,{raw:{width:pose.cell,height:pose.cell,channels:4}}).extract(rect).png().toBuffer();
  frames.push({image,w:rect.width,h:rect.height});
 }
 const maxW=rect.width+4,maxH=rect.height+4;
 const width=pose.columns*maxW,height=pose.rows*maxH;
 const rects=frames.map((f,k)=>({x:k%pose.columns*maxW+2,y:Math.floor(k/pose.columns)*maxH+2,w:f.w,h:f.h}));
 await sharp({create:{width,height,channels:4,background:{r:0,g:0,b:0,alpha:0}}}).composite(frames.map((f,k)=>({input:f.image,left:rects[k].x,top:rects[k].y}))).png().toFile(resolve(resources,'tiles',name+'.png'));
 catalog[name]={rects,width,height,projection:{shear:pose.shear||0,eye:pose.eye,rotation:pose.rotation}};
}
await writeFile(resolve(resources,'tile-atlas.json'),JSON.stringify(catalog));
const metrics=Object.fromEntries(Object.entries(catalog).map(([name,pose])=>[name,{w:pose.rects[0].w,h:pose.rects[0].h}]));
const metricsSource='// Generated by pack-tiles.mjs; camera crop dimensions.\nexport const TILE_POSE_METRICS: Record<string, { w: number; h: number }> = '+JSON.stringify(metrics)+';\n';
await writeFile(resolve(app,'shared/tile-pose-metrics.ts'),metricsSource);
await writeFile(resolve(app,'cocos-table/assets/scripts/tile-pose-metrics.ts'),metricsSource);
await copyFile(resolve(app,'shared/table-scene.ts'),resolve(app,'cocos-table/assets/scripts/table-scene.ts'));
await mkdir(resolve(resources,'art'),{recursive:true});
await copyFile(resolve(app,'public/art/table-straight-v4.png'),resolve(resources,'art/table.png'));
await copyFile(resolve(app,'public/avatars.png'),resolve(resources,'art/avatars.png'));
for(const name of ['pung','kong','concealed-kong','upgrade-kong','hu','self-draw'])await copyFile(resolve(app,`public/art/effects/${name}-gold-v1.png`),resolve(resources,`art/${name}.png`));
await copyFile(resolve(app,'public/art/effects/discard-pointer-gold-v1.png'),resolve(resources,'art/pointer.png'));
console.log('Packed',Object.keys(catalog).length,'Cocos pose atlases');
